version: '3.9'

services:
  app:
    build: .    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://localhost;http://localhost
    
    volumes:
      - .:/source