version: '3.9'

services:
  app:
    build: .
    ports:
      - 7298:7298
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://localhost;http://localhost
    
    volumes:
      - .:/source