version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    volumes:
      - .:/src:cached
